name: KeyKey
codename: keykey
description: >
  Autonomous key management and configuration agent
permissions:
  - git:read
  - git:write
  - cross_repo
triggers:
  - "/keykey"
  - "key update"
outputs:
  - summary_markdown
  - config_update
memory_tags:
  - keys
  - config
  - security